### ISSUE TITLE
Can't access server 

### ISSUE THREAD

**Issue by Alucard-Storm** [davidwhitman/wally#1]
Can ya change server path from alpha.wallhaven.cc to just wallhaven.cc. The app can't find wallpapers as they changed the server, I guess changing the path should do the trick.

**Comment by wispborne** [comment]
Let me know how the latest release works for you. Android has changed a lot and I modernized the code a little (no intentional changes to the app).

https://github.com/davidwhitman/wally/releases/tag/v1.6.1

You will need to **uninstall the previous version of Wally** to install this one (because I'm too lazy to go searching my old laptop for the signing key).

And thanks for bringing this to my attention! I had no idea that anybody used this fork.

**Comment by Alucard-Storm** [comment]
Working flawlessly, thanks for updating it.
By the way your fork is the most stable so far, no random crashes or any other bug. Keep up the good work 🙃

**Comment by wispborne** [comment]
Thank you!
